type Lang = 'fr' | 'en'

const strings = {
  fr: {
    // Header
    'nav.quote':     'Obtenir un devis',
    'nav.login':     'Connexion',
    'nav.dashboard': 'Mon espace',
    'nav.pilotage': 'Pilotage',
    // Chat
    'chat.welcome.title': 'Bonjour ! Je suis Neotravel,\nvotre assistant personnel.',
    'chat.welcome.sub':   'Décrivez-moi votre trajet et je calculerai votre devis en quelques instants.',
    'chat.hint': 'Entrée pour envoyer · Maj+Entrée pour un saut de ligne',
    'chat.ph.0': 'Ex : Paris → Lyon…',
    'chat.ph.1': 'Ex : 45 personnes…',
    'chat.ph.2': 'Aller simple ou aller-retour…',
    'chat.ph.3': 'Ex : 14 mai 2025…',
    'chat.qr.simple': 'Aller simple',
    'chat.qr.ar':     'Aller-retour',
    'chat.step2.ar':  'Aller-retour, parfait ! Quelle est la date de départ souhaitée ?',
    'chat.step2.as':  'Aller simple, noté ! Quelle est la date de départ souhaitée ?',
    'chat.refuse':    'Pas de problème ! Dites-moi votre nouveau trajet et je recalcule.',
    'chat.after':     'Souhaitez-vous modifier un critère ou faire une nouvelle demande ?',
    'chat.devis.ready': 'Voici votre devis personnalisé 👇',
    // Devis page
    'devis.accepted':    'Devis accepté !',
    'devis.accepted.sub': 'Votre demande de transport est enregistrée. Un conseiller vous contactera sous 24h.',
    'devis.title':   'Devis de transport de groupe',
    'devis.emitted': 'Émis le',
    'devis.ref':     'Référence',
    'devis.trip':    'Détails du trajet',
    'devis.services': 'Services inclus',
    'devis.pricing': 'Récapitulatif tarifaire',
    'devis.total':   'Total TTC',
    'devis.contact': 'Votre contact Neotravel',
    'devis.team':    'Équipe commerciale Neotravel',
    'devis.download': 'Télécharger PDF',
    'devis.new':     'Nouvelle demande',
    'devis.legal':   'Ce devis est non contractuel et reste valable 72 heures. Toute modification entraîne une révision tarifaire.',
    'devis.label.trajet':    'Trajet',
    'devis.label.date':      'Date de départ',
    'devis.label.pax':       'Passagers',
    'devis.label.vehicle':   'Véhicule',
    'devis.label.duration':  'Durée estimée',
    'devis.label.pax.unit':  'personnes',
    'devis.svc.driver':  'Chauffeur professionnel certifié',
    'devis.svc.insur':   'Assurance responsabilité civile incluse',
    'devis.svc.assist':  'Assistance 24h/24 en cas d\'incident',
    // Login
    'login.title': 'Bon retour !',
    'login.sub':   'Connectez-vous pour accéder à vos devis',
    'login.email': 'Adresse email',
    'login.pwd':   'Mot de passe',
    'login.btn':   'Se connecter',
    'login.no_account': 'Pas encore de compte ?',
    'login.register':   'Créer un compte',
    // Register
    'register.title':  'Créer un compte',
    'register.sub':    'Rejoignez Neotravel pour suivre vos devis',
    'register.first':  'Prénom',
    'register.last':   'Nom',
    'register.email':  'Adresse email',
    'register.pwd':    'Mot de passe',
    'register.btn':    'Créer mon compte',
    'register.has_account': 'Déjà un compte ?',
    'register.login':  'Se connecter',
    // Landing page
    'home.hero.highlighted': 'Obtenez un devis',
    'home.hero.before': 'Transport de groupe :',
    'home.hero.after': 'personnalisé en quelques minutes',
    'home.hero.sub': 'Notre assistant intelligent recueille vos besoins et calcule instantanément le meilleur tarif parmi nos partenaires autocaristes.',
    'home.hero.cta': 'Obtenir un devis',
    'home.hero.how': 'Voir comment ça marche',
    'home.badge.free': 'Sans engagement',
    'home.badge.fast': 'Réponse en 5 minutes',
    'home.badge.gdpr': 'RGPD conforme',
    'home.preview.online': 'En ligne',
    'home.preview.q': 'Bonjour ! Quel est votre itinéraire et le nombre de passagers ?',
    'home.preview.a': 'Paris → Lyon, 48 personnes, le 15 juillet',
    'home.preview.r': 'Parfait ! Je calcule votre devis…',
    'home.preview.ph': 'Votre réponse…',
    'home.adv.title': 'Avantages du service',
    'home.adv.sub': 'Une solution pensée pour simplifier chaque étape de votre demande de transport de groupe.',
    'home.how.title': 'Comment ça marche ?',
    'home.how.sub': 'En quelques étapes simples, obtenez votre devis et confirmez votre transport.',
    'home.how.cta': 'Démarrer maintenant',
    'home.footer.legal': 'Mentions légales',
    'home.footer.privacy': 'Politique de confidentialité',
    'home.footer.contact': 'Contact',
    // Dashboard
    'dashboard.title':    'Mon espace',
    'dashboard.logout':   'Déconnexion',
    'dashboard.new':      'Nouvelle demande',
    'dashboard.new.sub':  'Obtenir un devis en 2 minutes',
    'dashboard.history':  'Historique des devis',
    'dashboard.empty':    'Aucun devis pour l\'instant',
    'dashboard.empty.cta': 'Faire une demande →',
    'dashboard.devis':    'devis',
    'dashboard.in_history': 'dans votre historique',
    'dashboard.pdf':      'PDF',
    // Pilotage
    'pilotage.title':      'Pilotage commercial',
    'pilotage.sub':        'Vue d\'ensemble de l\'activité Neotravel',
    'pilotage.kpi.leads':   'Devis générés',
    'pilotage.kpi.leads.sub': 'volume total',
    'pilotage.kpi.conv':    'Taux de transformation',
    'pilotage.kpi.conv.sub': 'devis acceptés',
    'pilotage.kpi.delay':   'Délai moyen',
    'pilotage.kpi.delay.sub': 'jours avant validité',
    'pilotage.kpi.ca':      'CA potentiel',
    'pilotage.kpi.ca.sub':  'TTC, tous statuts',
    'pilotage.chart.status': 'Répartition par statut',
    'pilotage.chart.monthly': 'Volume de devis par mois',
    'pilotage.empty':       'Aucune donnée pour le moment',
    'pilotage.denied':      'Accès réservé à la direction',
  },
  en: {
    // Header
    'nav.quote':     'Get a quote',
    'nav.login':     'Sign in',
    'nav.dashboard': 'My account',
    'nav.pilotage': 'Dashboard',
    // Chat
    'chat.welcome.title': 'Hello ! I am Neotravel,\nyour personal assistant.',
    'chat.welcome.sub':   'Describe your journey and I will calculate your quote in a few moments.',
    'chat.hint': 'Enter to send · Shift+Enter for a new line',
    'chat.ph.0': 'E.g.: Paris → Lyon…',
    'chat.ph.1': 'E.g.: 45 passengers…',
    'chat.ph.2': 'One-way or round trip…',
    'chat.ph.3': 'E.g.: May 14, 2025…',
    'chat.qr.simple': 'One-way',
    'chat.qr.ar':     'Round trip',
    'chat.step2.ar':  'Round trip, perfect! What is your desired departure date?',
    'chat.step2.as':  'One-way, noted! What is your desired departure date?',
    'chat.refuse':    'No problem! Tell me your new journey and I\'ll recalculate.',
    'chat.after':     'Would you like to change a criterion or make a new request?',
    'chat.devis.ready': 'Here is your personalised quote 👇',
    // Devis page
    'devis.accepted':    'Quote accepted!',
    'devis.accepted.sub': 'Your transport request is registered. An advisor will contact you within 24h.',
    'devis.title':   'Group transport quote',
    'devis.emitted': 'Issued on',
    'devis.ref':     'Reference',
    'devis.trip':    'Journey details',
    'devis.services': 'Included services',
    'devis.pricing': 'Pricing summary',
    'devis.total':   'Total incl. VAT',
    'devis.contact': 'Your Neotravel contact',
    'devis.team':    'Neotravel sales team',
    'devis.download': 'Download PDF',
    'devis.new':     'New request',
    'devis.legal':   'This quote is non-binding and valid for 72 hours. Any changes will result in a revised quote.',
    'devis.label.trajet':    'Journey',
    'devis.label.date':      'Departure date',
    'devis.label.pax':       'Passengers',
    'devis.label.vehicle':   'Vehicle',
    'devis.label.duration':  'Estimated duration',
    'devis.label.pax.unit':  'passengers',
    'devis.svc.driver':  'Certified professional driver',
    'devis.svc.insur':   'Third-party liability insurance included',
    'devis.svc.assist':  '24/7 assistance in case of incident',
    // Login
    'login.title': 'Welcome back!',
    'login.sub':   'Sign in to access your quotes',
    'login.email': 'Email address',
    'login.pwd':   'Password',
    'login.btn':   'Sign in',
    'login.no_account': 'No account yet?',
    'login.register':   'Create an account',
    // Register
    'register.title':  'Create an account',
    'register.sub':    'Join Neotravel to track your quotes',
    'register.first':  'First name',
    'register.last':   'Last name',
    'register.email':  'Email address',
    'register.pwd':    'Password',
    'register.btn':    'Create my account',
    'register.has_account': 'Already have an account?',
    'register.login':  'Sign in',
    // Landing page
    'home.hero.highlighted': 'Get a quote',
    'home.hero.before': 'Group transport:',
    'home.hero.after': 'personalised in just a few minutes',
    'home.hero.sub': 'Our intelligent assistant gathers your needs and instantly calculates the best rate from our coach partners.',
    'home.hero.cta': 'Get a quote',
    'home.hero.how': 'See how it works',
    'home.badge.free': 'No commitment',
    'home.badge.fast': 'Response in 5 minutes',
    'home.badge.gdpr': 'GDPR compliant',
    'home.preview.online': 'Online',
    'home.preview.q': 'Hello! What is your itinerary and the number of passengers?',
    'home.preview.a': 'Paris → Lyon, 48 people, July 15th',
    'home.preview.r': 'Perfect! Calculating your quote…',
    'home.preview.ph': 'Your answer…',
    'home.adv.title': 'Service advantages',
    'home.adv.sub': 'A solution designed to simplify every step of your group transport request.',
    'home.how.title': 'How does it work?',
    'home.how.sub': 'In a few simple steps, get your quote and confirm your transport.',
    'home.how.cta': 'Get started now',
    'home.footer.legal': 'Legal notice',
    'home.footer.privacy': 'Privacy policy',
    'home.footer.contact': 'Contact',
    // Dashboard
    'dashboard.title':    'My account',
    'dashboard.logout':   'Sign out',
    'dashboard.new':      'New request',
    'dashboard.new.sub':  'Get a quote in 2 minutes',
    'dashboard.history':  'Quote history',
    'dashboard.empty':    'No quotes yet',
    'dashboard.empty.cta': 'Make a request →',
    'dashboard.devis':    'quotes',
    'dashboard.in_history': 'in your history',
    'dashboard.pdf':      'PDF',
    // Pilotage
    'pilotage.title':      'Commercial pilotage',
    'pilotage.sub':        'Overview of Neotravel activity',
    'pilotage.kpi.leads':   'Quotes generated',
    'pilotage.kpi.leads.sub': 'total volume',
    'pilotage.kpi.conv':    'Conversion rate',
    'pilotage.kpi.conv.sub': 'accepted quotes',
    'pilotage.kpi.delay':   'Average delay',
    'pilotage.kpi.delay.sub': 'days until validity',
    'pilotage.kpi.ca':      'Potential revenue',
    'pilotage.kpi.ca.sub':  'incl. VAT, all statuses',
    'pilotage.chart.status': 'Breakdown by status',
    'pilotage.chart.monthly': 'Quote volume per month',
    'pilotage.empty':       'No data yet',
    'pilotage.denied':      'Access restricted to management',
  }
} satisfies Record<Lang, Record<string, string>>

export const useLang = () => {
  const lang = useState<Lang>('lang', () => 'fr')

  function init() {
    if (!process.client) return
    const saved = localStorage.getItem('neotravel_lang')
    if (saved === 'fr' || saved === 'en') lang.value = saved as Lang
  }

  function setLang(l: Lang) {
    lang.value = l
    if (process.client) localStorage.setItem('neotravel_lang', l)
  }

  function t(key: string): string {
    return strings[lang.value][key as keyof typeof strings.fr]
      ?? strings.fr[key as keyof typeof strings.fr]
      ?? key
  }

  return { lang, init, setLang, t }
}
